name: main
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    container: cypress/included:8.3.1
    steps:
      - name: Repo-Checkout
        uses: actions/checkout@v2
      - run: npm install
      - run: cypress run
      - name: Archive screenshots
        uses: actions/upload-artifact@v2
        with:
          name: screenshot
          path: /__w/cod-devops/cod-devops/cypress/screenshots/*
      - name: Archive videos
        uses: actions/upload-artifact@v2
        with:
          name: video
          path: /__w/cod-devops/cod-devops/cypress/videos/*
  #    - name: Archive test result
  #      uses: actions/upload-artifact@v2
  #      with:
  #        name: result
  #        path: output.log
  #lippia-report:
  #  runs-on: ubuntu-20.04
  #  steps:
  #    - name: Get test result
  #      uses: actions/download-artifact@v2
  #      with:
  #        name: result


      